-- Add HSK 2 list and its 150 words

-- Seed HSK 2 list
INSERT INTO public.lists (name, slug, description, list_type, version) VALUES
  ('HSK 2 — 2010', 'hsk2', 'Official HSK 2 vocabulary list (150 words, new words beyond HSK 1).', 'hsk', '2010');

-- 150 HSK 2 words (unique to level 2, not in HSK 1)
INSERT INTO public.words (simplified,pinyin,pinyin_numeric,english_meaning,part_of_speech,classifier,example_sentence,example_translation) VALUES
('吧','ba','ba5','(modal particle: suggestion, assumption, or tag question)','particle',NULL,NULL,NULL),
('白','bái','bai2','white; in vain','adjective',NULL,NULL,NULL),
('百','bǎi','bai3','hundred','numeral',NULL,NULL,NULL),
('帮助','bāngzhù','bang1zhu4','to help; help','verb',NULL,NULL,NULL),
('报纸','bàozhǐ','bao4zhi3','newspaper','noun','份',NULL,NULL),
('比','bǐ','bi3','to compare; than','preposition',NULL,NULL,NULL),
('别','bié','bie2','don''t; other','adverb',NULL,NULL,NULL),
('宾馆','bīnguǎn','bin1guan3','hotel; guesthouse','noun','家',NULL,NULL),
('长','cháng','chang2','long','adjective',NULL,NULL,NULL),
('唱歌','chànggē','chang4ge1','to sing (a song)','verb',NULL,NULL,NULL),
('出','chū','chu1','to go out; to exit','verb',NULL,NULL,NULL),
('穿','chuān','chuan1','to wear; to put on','verb',NULL,NULL,NULL),
('次','cì','ci4','time (occurrence)','measure word',NULL,NULL,NULL),
('从','cóng','cong2','from; since','preposition',NULL,NULL,NULL),
('错','cuò','cuo4','wrong; mistake','adjective',NULL,NULL,NULL),
('打篮球','dǎ lánqiú','da3 lan2qiu2','to play basketball','phrase',NULL,NULL,NULL),
('大家','dàjiā','da4jia1','everyone; everybody','pronoun',NULL,NULL,NULL),
('到','dào','dao4','to arrive; to reach','verb',NULL,NULL,NULL),
('地方','dìfang','di4fang5','place; area','noun','个',NULL,NULL),
('地铁','dìtiě','di4tie3','subway; metro','noun','条',NULL,NULL),
('地图','dìtú','di4tu2','map','noun','张',NULL,NULL),
('东','dōng','dong1','east','noun',NULL,NULL,NULL),
('冬','dōng','dong1','winter','noun',NULL,NULL,NULL),
('房间','fángjiān','fang2jian1','room','noun','间',NULL,NULL),
('非常','fēicháng','fei1chang2','very; extremely','adverb',NULL,NULL,NULL),
('服务员','fúwùyuán','fu2wu4yuan2','waiter; service staff','noun','位',NULL,NULL),
('告诉','gàosu','gao4su5','to tell; to inform','verb',NULL,NULL,NULL),
('哥哥','gēge','ge1ge5','older brother','noun','个',NULL,NULL),
('给','gěi','gei3','to give; for','verb',NULL,NULL,NULL),
('公共汽车','gōnggòng qìchē','gong1gong4 qi4che1','(public) bus','noun','辆',NULL,NULL),
('公司','gōngsī','gong1si1','company; firm','noun','家',NULL,NULL),
('贵','guì','gui4','expensive; honorable','adjective',NULL,NULL,NULL),
('过','guò','guo4','to pass; to spend (time)','verb',NULL,NULL,NULL),
('还是','háishi','hai2shi5','or; still; had better','conjunction',NULL,NULL,NULL),
('孩子','háizi','hai2zi5','child','noun','个',NULL,NULL),
('好吃','hǎochī','hao3chi1','delicious; tasty','adjective',NULL,NULL,NULL),
('黑','hēi','hei1','black; dark','adjective',NULL,NULL,NULL),
('红','hóng','hong2','red','adjective',NULL,NULL,NULL),
('花','huā','hua1','flower; to spend (money/time)','noun/verb','朵',NULL,NULL),
('画','huà','hua4','to draw; picture; painting','verb/noun','幅',NULL,NULL),
('机场','jīchǎng','ji1chang3','airport','noun','个',NULL,NULL),
('鸡蛋','jīdàn','ji1dan4','chicken egg','noun','个',NULL,NULL),
('件','jiàn','jian4','measure word for clothes, matters','measure word',NULL,NULL,NULL),
('教室','jiàoshì','jiao4shi4','classroom','noun','间',NULL,NULL),
('姐姐','jiějie','jie3jie5','older sister','noun','个',NULL,NULL),
('介绍','jièshào','jie4shao4','to introduce; introduction','verb',NULL,NULL,NULL),
('进','jìn','jin4','to enter; to come in','verb',NULL,NULL,NULL),
('近','jìn','jin4','close; near','adjective',NULL,NULL,NULL),
('就','jiù','jiu4','then; right away; exactly','adverb',NULL,NULL,NULL),
('觉得','juéde','jue2de5','to feel; to think','verb',NULL,NULL,NULL),
('咖啡','kāfēi','ka1fei1','coffee','noun','杯',NULL,NULL),
('开始','kāishǐ','kai1shi3','to begin; beginning; start','verb/noun',NULL,NULL,NULL),
('考试','kǎoshì','kao3shi4','exam; test; to take an exam','noun/verb','次',NULL,NULL),
('可能','kěnéng','ke3neng2','maybe; possible; possibly','adverb/adjective',NULL,NULL,NULL),
('可以','kěyǐ','ke3yi3','can; may; okay','verb',NULL,NULL,NULL),
('课','kè','ke4','class; lesson; course','noun','节',NULL,NULL),
('快','kuài','kuai4','fast; quick; soon','adjective',NULL,NULL,NULL),
('快乐','kuàilè','kuai4le4','happy; joyful','adjective',NULL,NULL,NULL),
('累','lèi','lei4','tired; exhausted','adjective',NULL,NULL,NULL),
('离','lí','li2','away from; to leave','preposition',NULL,NULL,NULL),
('另外','lìngwài','ling4wai4','in addition; besides; other','conjunction',NULL,NULL,NULL),
('留学','liúxué','liu2xue2','to study abroad','verb',NULL,NULL,NULL),
('路','lù','lu4','road; route; way','noun','条',NULL,NULL),
('旅游','lǚyóu','lv3you2','to travel; tour; tourism','verb/noun',NULL,NULL,NULL),
('卖','mài','mai4','to sell','verb',NULL,NULL,NULL),
('慢','màn','man4','slow','adjective',NULL,NULL,NULL),
('忙','máng','mang2','busy','adjective',NULL,NULL,NULL),
('每','měi','mei3','every; each','adjective',NULL,NULL,NULL),
('妹妹','mèimei','mei4mei5','younger sister','noun','个',NULL,NULL),
('门','mén','men2','door; gate','noun','扇',NULL,NULL),
('面条','miàntiáo','mian4tiao2','noodles','noun','碗',NULL,NULL),
('明白','míngbai','ming2bai5','to understand; clear; obvious','verb/adjective',NULL,NULL,NULL),
('拿','ná','na2','to take; to hold; to bring','verb',NULL,NULL,NULL),
('男','nán','nan2','male; man; son','noun/adjective',NULL,NULL,NULL),
('您','nín','nin2','you (polite form)','pronoun',NULL,NULL,NULL),
('牛奶','niúnǎi','niu2nai3','milk','noun','杯',NULL,NULL),
('女','nǚ','nu:3','female; woman; daughter','noun/adjective',NULL,NULL,NULL),
('旁边','pángbiān','pang2bian1','beside; next to; side','noun',NULL,NULL,NULL),
('胖','pàng','pang4','fat; overweight; chubby','adjective',NULL,NULL,NULL),
('跑步','pǎobù','pao3bu4','to run; jogging','verb',NULL,NULL,NULL),
('便宜','piányí','pian2yi5','cheap; inexpensive','adjective',NULL,NULL,NULL),
('起床','qǐchuáng','qi3chuang2','to get up; to get out of bed','verb',NULL,NULL,NULL),
('让','ràng','rang4','to let; to allow; to make','verb',NULL,NULL,NULL),
('如果','rúguǒ','ru2guo3','if; in case','conjunction',NULL,NULL,NULL),
('身体','shēntǐ','shen1ti3','body; health; physical condition','noun','个',NULL,NULL),
('生病','shēngbìng','sheng1bing4','to be sick; to fall ill','verb',NULL,NULL,NULL),
('生日','shēngrì','sheng1ri4','birthday','noun','个',NULL,NULL),
('时间','shíjiān','shi2jian1','time; period; duration','noun',NULL,NULL,NULL),
('事情','shìqing','shi4qing5','matter; affair; thing','noun','件',NULL,NULL),
('手机','shǒujī','shou3ji1','mobile phone; cell phone','noun','部',NULL,NULL),
('说话','shuōhuà','shuo1hua4','to speak; to talk','verb',NULL,NULL,NULL),
('送','sòng','song4','to give; to send; to see off','verb',NULL,NULL,NULL),
('虽然','suīrán','sui1ran2','although; though; even though','conjunction',NULL,NULL,NULL),
('所以','suǒyǐ','suo3yi3','therefore; so; as a result','conjunction',NULL,NULL,NULL),
('它','tā','ta1','it (non-human)','pronoun',NULL,NULL,NULL),
('特别','tèbié','te4bie2','special; especially; particularly','adjective/adverb',NULL,NULL,NULL),
('踢足球','tī zúqiú','ti1 zu2qiu2','to play soccer / football','phrase',NULL,NULL,NULL),
('题','tí','ti2','question; problem; topic; title','noun','道',NULL,NULL),
('跳舞','tiàowǔ','tiao4wu3','to dance','verb',NULL,NULL,NULL),
('外','wài','wai4','outside; other; foreign','noun/adjective',NULL,NULL,NULL),
('完','wán','wan2','to finish; done; complete','verb',NULL,NULL,NULL),
('晚上','wǎnshang','wan3shang5','evening; night','noun',NULL,NULL,NULL),
('为什么','wèishéme','wei4she2me5','why','pronoun',NULL,NULL,NULL),
('问','wèn','wen4','to ask; to inquire','verb',NULL,NULL,NULL),
('问题','wèntí','wen4ti2','question; problem; issue','noun','个',NULL,NULL),
('西','xī','xi1','west','noun',NULL,NULL,NULL),
('希望','xīwàng','xi1wang4','to hope; hope; wish','verb/noun',NULL,NULL,NULL),
('向','xiàng','xiang4','toward; to; in the direction of','preposition',NULL,NULL,NULL),
('新','xīn','xin1','new','adjective',NULL,NULL,NULL),
('颜色','yánsè','yan2se4','color','noun','种',NULL,NULL),
('眼睛','yǎnjing','yan3jing5','eye','noun','只',NULL,NULL),
('羊肉','yángròu','yang2rou4','mutton; lamb','noun',NULL,NULL,NULL),
('一般','yībān','yi1ban1','ordinary; general; usually; normally','adjective/adverb',NULL,NULL,NULL),
('一共','yīgòng','yi1gong4','altogether; in total','adverb',NULL,NULL,NULL),
('以为','yǐwéi','yi3wei2','to think (mistakenly); to assume','verb',NULL,NULL,NULL),
('已经','yǐjīng','yi3jing1','already','adverb',NULL,NULL,NULL),
('因为','yīnwèi','yin1wei4','because; since; as','conjunction',NULL,NULL,NULL),
('音乐','yīnyuè','yin1yue4','music','noun',NULL,NULL,NULL),
('游泳','yóuyǒng','you2yong3','to swim; swimming','verb',NULL,NULL,NULL),
('有名','yǒumíng','you3ming2','famous; well-known','adjective',NULL,NULL,NULL),
('鱼','yú','yu2','fish','noun','条',NULL,NULL),
('远','yuǎn','yuan3','far; distant','adjective',NULL,NULL,NULL),
('运动','yùndòng','yun4dong4','exercise; sport; movement','noun/verb','项',NULL,NULL),
('再','zài','zai4','again; once more','adverb',NULL,NULL,NULL),
('早上','zǎoshang','zao3shang5','morning; early morning','noun',NULL,NULL,NULL),
('站','zhàn','zhan4','to stand; station; stop','verb/noun','个',NULL,NULL),
('张','zhāng','zhang1','measure word for flat objects; (surname)','measure word',NULL,NULL,NULL),
('找','zhǎo','zhao3','to look for; to find; to give change','verb',NULL,NULL,NULL),
('着','zhe','zhe5','(aspect particle indicating ongoing state/action)','particle',NULL,NULL,NULL),
('正在','zhèngzài','zheng4zai4','in the process of; right now; -ing','adverb',NULL,NULL,NULL),
('知道','zhīdào','zhi1dao4','to know; to be aware of','verb',NULL,NULL,NULL),
('中间','zhōngjiān','zhong1jian1','middle; center; between; among','noun',NULL,NULL,NULL),
('中文','Zhōngwén','Zhong1wen2','Chinese (written language)','noun',NULL,NULL,NULL),
('重要','zhòngyào','zhong4yao4','important; significant','adjective',NULL,NULL,NULL),
('注意','zhùyì','zhu4yi4','to pay attention; to be careful','verb',NULL,NULL,NULL),
('走','zǒu','zou3','to walk; to leave; to go','verb',NULL,NULL,NULL),
('最','zuì','zui4','most; -est (superlative)','adverb',NULL,NULL,NULL),
('左边','zuǒbiān','zuo3bian1','left side; to the left','noun',NULL,NULL,NULL),
('奶奶','nǎinai','nai3nai5','(paternal) grandmother','noun',NULL,NULL,NULL),
('爷爷','yéye','ye2ye5','(paternal) grandfather','noun',NULL,NULL,NULL),
('一起','yīqǐ','yi1qi3','together; at the same time','adverb',NULL,NULL,NULL),
('右边','yòubiān','you4bian1','right side; to the right','noun',NULL,NULL,NULL),
('上班','shàngbān','shang4ban1','to go to work; to start work','verb',NULL,NULL,NULL),
('下班','xiàbān','xia4ban1','to get off work; to finish work','verb',NULL,NULL,NULL),
('日','rì','ri4','day; sun; Japan (abbrev.)','noun',NULL,NULL,NULL),
('带','dài','dai4','to bring; to carry; to take along','verb',NULL,NULL,NULL),
('等','děng','deng3','to wait; to wait for','verb',NULL,NULL,NULL),
('结婚','jiéhūn','jie2hun1','to get married; to marry','verb',NULL,NULL,NULL),
('那么','nàme','na4me5','then; in that case; so','conjunction/adverb',NULL,NULL,NULL),
('但是','dànshì','dan4shi4','but; however','conjunction',NULL,NULL,NULL);

-- Link all HSK 2 words to the hsk2 list
INSERT INTO public.word_lists (word_id,list_id,position)
SELECT w.id, l.id, wl.position
FROM public.lists l
JOIN (VALUES
  ('hsk2','吧',0),('hsk2','白',1),('hsk2','百',2),('hsk2','帮助',3),('hsk2','报纸',4),('hsk2','比',5),('hsk2','别',6),('hsk2','宾馆',7),('hsk2','长',8),('hsk2','唱歌',9),
  ('hsk2','出',10),('hsk2','穿',11),('hsk2','次',12),('hsk2','从',13),('hsk2','错',14),('hsk2','打篮球',15),('hsk2','大家',16),('hsk2','到',17),('hsk2','地方',18),('hsk2','地铁',19),
  ('hsk2','地图',20),('hsk2','东',21),('hsk2','冬',22),('hsk2','房间',23),('hsk2','非常',24),('hsk2','服务员',25),('hsk2','告诉',26),('hsk2','哥哥',27),('hsk2','给',28),('hsk2','公共汽车',29),
  ('hsk2','公司',30),('hsk2','贵',31),('hsk2','过',32),('hsk2','还是',33),('hsk2','孩子',34),('hsk2','好吃',35),('hsk2','黑',36),('hsk2','红',37),('hsk2','花',38),('hsk2','画',39),
  ('hsk2','机场',40),('hsk2','鸡蛋',41),('hsk2','件',42),('hsk2','教室',43),('hsk2','姐姐',44),('hsk2','介绍',45),('hsk2','进',46),('hsk2','近',47),('hsk2','就',48),('hsk2','觉得',49),
  ('hsk2','咖啡',50),('hsk2','开始',51),('hsk2','考试',52),('hsk2','可能',53),('hsk2','可以',54),('hsk2','课',55),('hsk2','快',56),('hsk2','快乐',57),('hsk2','累',58),('hsk2','离',59),
  ('hsk2','另外',60),('hsk2','留学',61),('hsk2','路',62),('hsk2','旅游',63),('hsk2','卖',64),('hsk2','慢',65),('hsk2','忙',66),('hsk2','每',67),('hsk2','妹妹',68),('hsk2','门',69),
  ('hsk2','面条',70),('hsk2','明白',71),('hsk2','拿',72),('hsk2','男',73),('hsk2','您',74),('hsk2','牛奶',75),('hsk2','女',76),('hsk2','旁边',77),('hsk2','胖',78),('hsk2','跑步',79),
  ('hsk2','便宜',80),('hsk2','起床',81),('hsk2','让',82),('hsk2','如果',83),('hsk2','身体',84),('hsk2','生病',85),('hsk2','生日',86),('hsk2','时间',87),('hsk2','事情',88),('hsk2','手机',89),
  ('hsk2','说话',90),('hsk2','送',91),('hsk2','虽然',92),('hsk2','所以',93),('hsk2','它',94),('hsk2','特别',95),('hsk2','踢足球',96),('hsk2','题',97),('hsk2','跳舞',98),('hsk2','外',99),
  ('hsk2','完',100),('hsk2','晚上',101),('hsk2','为什么',102),('hsk2','问',103),('hsk2','问题',104),('hsk2','西',105),('hsk2','希望',106),('hsk2','向',107),('hsk2','新',108),('hsk2','颜色',109),
  ('hsk2','眼睛',110),('hsk2','羊肉',111),('hsk2','一般',112),('hsk2','一共',113),('hsk2','以为',114),('hsk2','已经',115),('hsk2','因为',116),('hsk2','音乐',117),('hsk2','游泳',118),('hsk2','有名',119),
  ('hsk2','鱼',120),('hsk2','远',121),('hsk2','运动',122),('hsk2','再',123),('hsk2','早上',124),('hsk2','站',125),('hsk2','张',126),('hsk2','找',127),('hsk2','着',128),('hsk2','正在',129),
  ('hsk2','知道',130),('hsk2','中间',131),('hsk2','中文',132),('hsk2','重要',133),('hsk2','注意',134),('hsk2','走',135),('hsk2','最',136),('hsk2','左边',137),('hsk2','奶奶',138),('hsk2','爷爷',139),
  ('hsk2','一起',140),('hsk2','右边',141),('hsk2','上班',142),('hsk2','下班',143),('hsk2','日',144),('hsk2','带',145),('hsk2','等',146),('hsk2','结婚',147),('hsk2','那么',148),('hsk2','但是',149)
) AS wl(slug,simplified,position)
  ON l.slug = wl.slug
JOIN public.words w ON w.simplified = wl.simplified;
